import React from "react";
import Register from "../components/register/Register";

export const metadata = {
  title: "Mi turno | Register",
  description: "Generated by create next app",
};

const register = () => {
  return (
    <>
      <Register />
    </>
  );
};

export default register;
